version: '3.8'

services:
  node-1:
    build: .
    container_name: node-1
    hostname: node-1
    ports:
      - "80:80"
    volumes:
      - ./shared_code:/app
      - ./databases/node-1:/databases
    networks:
      my_network:
        aliases:
          - node-1
  database:
    container_name: node-1-database
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/host-machine
      - ./persistent:/var/lib/mysql
    networks:
      my_network:
        aliases:
          - node-1-database
networks:
  my_network:
    driver: bridge
