version: '3.8'

services:
  node-1:
    build: .
    container_name: node-1
    hostname: node-1
    ports:
      - "8081:80"
    volumes:
      - ./shared_code:/app
      - ./databases/node-1:/databases
    networks:
      node-1-network:
        aliases:
          - node-1
      shared_network:
        aliases:
          - node-1
  database:
    container_name: node-1-database
    build:
      context: .
      dockerfile: Dockerfile-mysql
    ports:
      - "3301:3306"
    environment:
      MYSQL_DATABASE: node
      MYSQL_USER: node
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/host-machine
      - ./persistent:/var/lib/mysql
    networks:
      node-1-network:
        aliases:
          - node-1-database

networks:
  node-1-network:
    name: node-1-network
    driver: bridge
  shared_network:
    external: true